<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreLiveLearningRequest;
use App\Http\Requests\UpdateLiveLearningRequest;
use App\Http\Resources\LiveLearningResource;
use App\Http\Resources\LiveLearningRegistrationResource;
use App\Models\LiveLearning;
use App\Models\LiveLearningRegistration;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Cell\DataType;

class AdminLiveLearningController extends Controller
{
    /**
     * Display a listing of live learnings (Admin)
     * GET /api/admin/live-learnings
     * 
     * Supports filtering, sorting, pagination
     * Shows all status including draft and deleted
     */
    public function index(Request $request)
    {
        try {
            $query = LiveLearning::query()
                ->with('creator')
                ->withCount('registrations');

            // Include soft deleted items if requested
            if ($request->has('filter.with_trashed') && $request->input('filter.with_trashed')) {
                $query->withTrashed();
            }

            // Filter by status
            if ($request->has('filter.status')) {
                $query->where('status', $request->input('filter.status'));
            }

            // Filter by is_paid
            if ($request->has('filter.is_paid')) {
                $isPaid = filter_var($request->input('filter.is_paid'), FILTER_VALIDATE_BOOLEAN);
                $query->where('is_paid', $isPaid);
            }

            // Filter by title (search)
            if ($request->has('filter.title')) {
                $query->where('title', 'like', '%' . $request->input('filter.title') . '%');
            }

            // Filter by created_by
            if ($request->has('filter.created_by')) {
                $query->where('created_by', $request->input('filter.created_by'));
            }

            // Sorting
            $sortField = $request->input('sort', '-created_at'); // Default: newest first
            $sortDirection = 'asc';
            
            if (Str::startsWith($sortField, '-')) {
                $sortDirection = 'desc';
                $sortField = Str::substr($sortField, 1);
            }

            // Allowed sort fields
            $allowedSortFields = ['created_at', 'updated_at', 'title', 'schedule', 'status', 'registrations_count'];
            if (in_array($sortField, $allowedSortFields)) {
                if ($sortField === 'registrations_count') {
                    $query->orderBy('registrations_count', $sortDirection);
                } else {
                    $query->orderBy($sortField, $sortDirection);
                }
            }

            // Pagination
            $perPage = $request->input('per_page', 15);
            $liveLearnings = $query->paginate($perPage);

            return LiveLearningResource::collection($liveLearnings);

        } catch (\Exception $exception) {
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Store a new live learning
     * POST /api/admin/live-learnings
     */
    public function store(StoreLiveLearningRequest $request): JsonResponse
    {
        try {
            DB::beginTransaction();

            $data = $request->validated();
            
            // Set created_by to authenticated user
            $data['created_by'] = auth()->id();

            // Create live learning (slug will be auto-generated by Sluggable trait)
            $liveLearning = LiveLearning::create($data);

            DB::commit();

            return response()->json([
                'meta' => [
                    'message' => 'Live Learning berhasil dibuat',
                    'code' => 201,
                ],
                'data' => new LiveLearningResource($liveLearning),
            ], 201);

        } catch (\Exception $exception) {
            DB::rollBack();
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Display a single live learning by ID (Admin)
     * GET /api/admin/live-learnings/{id}
     */
    public function show($id)
    {
        try {
            $liveLearning = LiveLearning::with('creator', 'updater', 'deleter')
                ->withCount('registrations')
                ->withTrashed()
                ->findOrFail($id);

            return new LiveLearningResource($liveLearning);

        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json([
                'meta' => [
                    'message' => 'Live Learning tidak ditemukan',
                    'code' => 404,
                ],
            ], 404);
        } catch (\Exception $exception) {
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Update a live learning
     * PUT /api/admin/live-learnings/{id}
     */
    public function update(UpdateLiveLearningRequest $request, $id): JsonResponse
    {
        try {
            DB::beginTransaction();

            $liveLearning = LiveLearning::findOrFail($id);

            $data = $request->validated();
            
            // Set updated_by to authenticated user
            $data['updated_by'] = auth()->id();

            // Update live learning (slug will be auto-updated if title changes)
            $liveLearning->update($data);

            DB::commit();

            return response()->json([
                'meta' => [
                    'message' => 'Live Learning berhasil diupdate',
                    'code' => 200,
                ],
                'data' => new LiveLearningResource($liveLearning->fresh()),
            ], 200);

        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            DB::rollBack();
            return response()->json([
                'meta' => [
                    'message' => 'Live Learning tidak ditemukan',
                    'code' => 404,
                ],
            ], 404);
        } catch (\Exception $exception) {
            DB::rollBack();
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Delete a live learning (soft delete)
     * DELETE /api/admin/live-learnings/{id}
     */
    public function destroy($id): JsonResponse
    {
        try {
            $liveLearning = LiveLearning::findOrFail($id);

            // Set deleted_by before soft delete
            $liveLearning->deleted_by = auth()->id();
            $liveLearning->save();
            
            // Soft delete
            $liveLearning->delete();

            return response()->json([
                'meta' => [
                    'message' => 'Live Learning berhasil dihapus',
                    'code' => 200,
                ],
            ], 200);

        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json([
                'meta' => [
                    'message' => 'Live Learning tidak ditemukan',
                    'code' => 404,
                ],
            ], 404);
        } catch (\Exception $exception) {
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Get registrations for a specific live learning
     * GET /api/admin/live-learnings/{id}/registrations
     */
    public function registrations(Request $request, $id)
    {
        try {
            // Check if live learning exists
            $liveLearning = LiveLearning::withTrashed()->findOrFail($id);

            $query = LiveLearningRegistration::where('live_learning_id', $id)
                ->with('liveLearning');

            // Search by name or email
            if ($request->has('filter.search')) {
                $search = $request->input('filter.search');
                $query->search($search);
            }

            // Date range filter
            if ($request->has('filter.date_from') && $request->has('filter.date_to')) {
                $query->dateRange(
                    $request->input('filter.date_from'),
                    $request->input('filter.date_to')
                );
            }

            // Sorting
            $sortField = $request->input('sort', '-registered_at'); // Default: newest first
            $sortDirection = 'asc';
            
            if (Str::startsWith($sortField, '-')) {
                $sortDirection = 'desc';
                $sortField = Str::substr($sortField, 1);
            }

            $allowedSortFields = ['registered_at', 'name', 'email', 'created_at'];
            if (in_array($sortField, $allowedSortFields)) {
                $query->orderBy($sortField, $sortDirection);
            }

            // Pagination
            $perPage = $request->input('per_page', 15);
            $registrations = $query->paginate($perPage);

            return LiveLearningRegistrationResource::collection($registrations);

        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json([
                'meta' => [
                    'message' => 'Live Learning tidak ditemukan',
                    'code' => 404,
                ],
            ], 404);
        } catch (\Exception $exception) {
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Get all registrations from all live learnings
     * GET /api/admin/live-learning-registrations
     */
    public function allRegistrations(Request $request)
    {
        try {
            $query = LiveLearningRegistration::with('liveLearning');

            // Filter by live learning ID
            if ($request->has('filter.live_learning_id')) {
                $query->where('live_learning_id', $request->input('filter.live_learning_id'));
            }

            // Search by name, email, or whatsapp
            if ($request->has('filter.search')) {
                $search = $request->input('filter.search');
                $query->search($search);
            }

            // Date range filter
            if ($request->has('filter.date_from') && $request->has('filter.date_to')) {
                $query->dateRange(
                    $request->input('filter.date_from'),
                    $request->input('filter.date_to')
                );
            }

            // Sorting
            $sortField = $request->input('sort', '-registered_at');
            $sortDirection = 'asc';
            
            if (Str::startsWith($sortField, '-')) {
                $sortDirection = 'desc';
                $sortField = Str::substr($sortField, 1);
            }

            $allowedSortFields = ['registered_at', 'name', 'email', 'created_at'];
            if (in_array($sortField, $allowedSortFields)) {
                $query->orderBy($sortField, $sortDirection);
            }

            // Pagination
            $perPage = $request->input('per_page', 15);
            $registrations = $query->paginate($perPage);

            return LiveLearningRegistrationResource::collection($registrations);

        } catch (\Exception $exception) {
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Delete a registration
     * DELETE /api/admin/live-learning-registrations/{id}
     */
    public function destroyRegistration($id): JsonResponse
    {
        try {
            $registration = LiveLearningRegistration::findOrFail($id);
            
            $registration->delete();

            return response()->json([
                'meta' => [
                    'message' => 'Registrasi berhasil dihapus',
                    'code' => 200,
                ],
            ], 200);

        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json([
                'meta' => [
                    'message' => 'Registrasi tidak ditemukan',
                    'code' => 404,
                ],
            ], 404);
        } catch (\Exception $exception) {
            return $this->responseError($exception, [], 500);
        }
    }

    /**
     * Export registrations to Excel
     * GET /api/admin/live-learnings/{id}/registrations/export
     */
    public function exportRegistrations($id)
    {
        try {
            // Get live learning dengan registrations
            $liveLearning = LiveLearning::with('registrations')->findOrFail($id);
            $registrations = $liveLearning->registrations;

            // Buat spreadsheet baru
            $spreadsheet = new Spreadsheet();
            $sheet = $spreadsheet->getActiveSheet();

            // Set header
            $sheet->setCellValue('A1', 'Name');
            $sheet->setCellValue('B1', 'Email');
            $sheet->setCellValue('C1', 'WhatsApp');

            // Style header - Bold dan background color
            $headerStyle = [
                'font' => ['bold' => true],
                'fill' => [
                    'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                    'startColor' => ['rgb' => 'E2E8F0']
                ]
            ];
            $sheet->getStyle('A1:C1')->applyFromArray($headerStyle);

            // Isi data mulai dari row 2
            $row = 2;
            foreach ($registrations as $registration) {
                // Set Name
                $sheet->setCellValue('A' . $row, $registration->name ?? $registration->full_name ?? '');
                
                // Set Email
                $sheet->setCellValue('B' . $row, $registration->email ?? '');
                
                // Set WhatsApp - PENTING: Format sebagai TEXT biar ga jadi scientific notation
                $whatsapp = $registration->whatsapp 
                    ?? $registration->whatsapp_number 
                    ?? $registration->phone 
                    ?? $registration->phone_number 
                    ?? '';
                
                $sheet->setCellValueExplicit(
                    'C' . $row, 
                    $whatsapp,
                    DataType::TYPE_STRING // Paksa sebagai string/text
                );
                
                $row++;
            }

            // Auto size columns
            $sheet->getColumnDimension('A')->setAutoSize(true);
            $sheet->getColumnDimension('B')->setAutoSize(true);
            $sheet->getColumnDimension('C')->setWidth(20);

            // Buat writer
            $writer = new Xlsx($spreadsheet);
            
            // Nama file
            $filename = 'live-learning-' . ($liveLearning->slug ?? $liveLearning->id) . '-registrations.xlsx';
            
            // Output ke file temporary
            $temp_file = tempnam(sys_get_temp_dir(), 'export_');
            $writer->save($temp_file);

            // Return file sebagai download response
            return response()->download($temp_file, $filename, [
                'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            ])->deleteFileAfterSend(true);
            
        } catch (\Illuminate\Database\Eloquent\ModelNotFoundException $e) {
            return response()->json([
                'meta' => [
                    'message' => 'Live Learning tidak ditemukan',
                    'code' => 404,
                ],
            ], 404);
        } catch (\Exception $exception) {
            return $this->responseError($exception, [], 500);
        }
    }
}